/*
 * POSEIDON: an agent-based model of fisheries
 * Copyright (c) 2025, University of Oxford.
 *
 * University of Oxford means the Chancellor, Masters and Scholars of the
 * University of Oxford, having an administrative office at Wellington
 * Square, Oxford OX1 2JD, UK.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "SURIMI-POSEIDON"
includeBuild("POSEIDON") {
    dependencySubstitution {
        substitute(module("POSEIDON:agents")).using(project(":agents"))
        substitute(module("POSEIDON:biology")).using(project(":biology"))
        substitute(module("POSEIDON:examples")).using(project(":examples"))
        substitute(module("POSEIDON:gui")).using(project(":gui"))
        substitute(module("POSEIDON:io")).using(project(":io"))
        substitute(module("POSEIDON:regulations")).using(project(":regulations"))
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        // Resolve Buf-generated artifacts only from Buf's Maven repo.
        // This avoids hitting other repos (and failing the build) if one of them is temporarily unreachable.
        exclusiveContent {
            forRepository {
                maven {
                    name = "buf"
                    url = uri("https://buf.build/gen/maven")
                }
            }
            filter {
                includeGroupByRegex("build\\.buf\\.gen")
            }
        }
        maven {
            // needs to come before Maven Central, otherwise we fail to find javax.media:jai_core:1.1.3
            url = uri("https://repo.osgeo.org/repository/geotools-releases/")
        }
        mavenCentral()
        maven { url = uri("https://maven.geo-solutions.it/") }
        maven {
            // needs to come after mavenCentral otherwise we fail to find
            // flatlaf-3.5.1-macos-arm64.dylib and flatlaf-3.5.1-macos-x86_64.dylib
            url = uri("https://nexus.geomatys.com/repository/maven-public/")
        }
        maven("https://jitpack.io")
    }
}
