/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.project.surimi.poseidon;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ServerTest {
    @Test void appHasAGreeting() {
        Server classUnderTest = new Server();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
