[versions]
grpc = "1.71.0"
lombok = "1.18.30"
opentelemetry-core = "1.49.0"
opentelemetry-instrumentation = "2.14.0-alpha"
spotbugs = "6.0.26"
jcommander = "2.0"
jqwik = "1.9.2"
commons-beanutils = "1.11.0"
commons-io = "2.19.0"

[libraries]
commons-beanutils = { module = "commons-beanutils:commons-beanutils", version.ref = "commons-beanutils" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry-core" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "opentelemetry-core" }
opentelemetry-grpc-server = { module = "io.opentelemetry.instrumentation:opentelemetry-grpc-1.6", version.ref = "opentelemetry-instrumentation" }
opentelemetry-sdk = { module = "io.opentelemetry:opentelemetry-sdk", version.ref = "opentelemetry-core" }
jcommander = { module = "org.jcommander:jcommander", version.ref = "jcommander" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations" }

[bundles]
opentelemetry = [
    "opentelemetry-api",
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp",
    "opentelemetry-grpc-server"
]

[plugins]
shadow = { id = "com.gradleup.shadow", version = "8.3.5" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }
