/*
 * POSEIDON: an agent-based model of fisheries
 * Copyright (c) 2025, University of Oxford.
 *
 * University of Oxford means the Chancellor, Masters and Scholars of the
 * University of Oxford, having an administrative office at Wellington
 * Square, Oxford OX1 2JD, UK.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.project.surimi.poseidon.server;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import com.beust.jcommander.ParameterException;
import com.google.protobuf.Timestamp;
import eu.project.surimi.poseidon.ProtocolVersionExtractor;
import eu.project.surimi.poseidon.server.catchprovider.GetCatchDispositionSummaryRequestHandler;
import eu.project.surimi.poseidon.server.ecology.UpdateBiomassRequestHandler;
import eu.project.surimi.poseidon.server.fishery.FisheryService;
import eu.project.surimi.poseidon.server.prices.UpdateSpeciesPricesRequestHandler;
import eu.project.surimi.poseidon.server.regulations.GetFishingActivityRequestHandler;
import eu.project.surimi.poseidon.server.regulations.UpdateRegulationsRequestHandler;
import eu.project.surimi.poseidon.server.sales.GetSalesRequestHandler;
import eu.project.surimi.poseidon.server.simulation.*;
import io.grpc.ServerInterceptor;
import io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder;
import io.grpc.protobuf.services.ProtoReflectionServiceV1;
import io.opentelemetry.instrumentation.grpc.v1_6.GrpcTelemetry;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import uk.ac.ox.poseidon.core.utils.CustomPathConverter;
import uk.ac.ox.poseidon.io.ScenarioLoader;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.file.Path;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Map;

import static eu.project.surimi.poseidon.server.OpenTelemetryConfiguration.openTelemetry;
import static java.lang.System.Logger.Level.INFO;
import static java.time.ZoneOffset.UTC;

@NoArgsConstructor
@AllArgsConstructor
public class Server {

    private static final System.Logger logger = System.getLogger(Server.class.getName());
    public static final String PROTOCOL_VERSION =
        ProtocolVersionExtractor.getSurimiProtocolVersion();

    @Parameter(
        names = {"-s", "--scenario"},
        description = "Path to the scenario file in YAML format.",
        converter = CustomPathConverter.class,
        required = true
    )
    private Path scenarioPath;

    @Parameter(
        names = {"-p", "--port"},
        description = "Port to listen on for gRPC requests.",
        required = true
    )
    private int port;

    static void main(final String[] args) {
        logger.log(INFO, () -> "Received arguments: " + Arrays.toString(args));
        final Server server = new Server();
        final JCommander jCommander = JCommander
            .newBuilder()
            .addObject(server)
            .build();
        try {
            jCommander.parse(args);
            final io.grpc.Server grpcServer = server.startServer(new SimulationManager());
            grpcServer.awaitTermination();
        } catch (final ParameterException | IOException | InterruptedException e) {
            System.err.println(e.getMessage());
        }
    }

    io.grpc.Server startServer(final SimulationManager simulationManager) throws IOException,
        InterruptedException {
        final io.grpc.Server grpcServer = NettyServerBuilder
            // Bind to 0.0.0.0 so the server listens on all network interfaces
            .forAddress(new InetSocketAddress("0.0.0.0", this.port))
            
            //.addService(ProtoReflectionService.newInstance()) // deprecated, but works with
            // postman
            .addService(ProtoReflectionServiceV1.newInstance())
            .intercept(new ExceptionInterceptor())
            .intercept(GrpcTelemetry.create(openTelemetry).newServerInterceptor())
            .intercept(createTrailerInterceptor())
            .addService(createFisheryService(simulationManager))
            .build();
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            logger.log(INFO, "Shutting down gRPC server...");
            grpcServer.shutdown();
            logger.log(INFO, "Server shut down.");
        }));
        grpcServer.start();
        logger.log(INFO, "Server started, listening on " + port);
        return grpcServer;
    }

    private ServerInterceptor createTrailerInterceptor() {
        return new TrailerInterceptor(Map.of("protocol-version", PROTOCOL_VERSION));
    }

    private FisheryService createFisheryService(final SimulationManager simulationManager) {
        return new FisheryService(
            new InitialiseRequestHandler(
                simulationManager,
                new ScenarioLoader("eu.project.surimi"),
                scenarioPath.toFile()
            ),
            new SimulateStepRequestHandler(simulationManager),
            new FinaliseRequestHandler(simulationManager),
            new CancelRequestHandler(simulationManager),
            new GetCatchDispositionSummaryRequestHandler(simulationManager),
            new UpdateBiomassRequestHandler(simulationManager),
            new GetFishingActivityRequestHandler(simulationManager),
            new UpdateRegulationsRequestHandler(simulationManager),
            new GetSalesRequestHandler(simulationManager),
            new UpdateSpeciesPricesRequestHandler(simulationManager),
            new GetProtocolVersionRequestHandler()
        );
    }

    public static Instant toInstant(
        final Timestamp timestamp
    ) {
        return toOffsetDateTime(timestamp).toInstant();
    }

    private static OffsetDateTime toOffsetDateTime(final Timestamp timestamp) {
        return Instant
            .ofEpochSecond(timestamp.getSeconds(), timestamp.getNanos())
            .atOffset(UTC);
    }

    public static LocalDateTime toLocalDateTime(
        final Timestamp timestamp
    ) {
        return toOffsetDateTime(timestamp).toLocalDateTime();
    }

    public static Timestamp toTimestamp(
        final LocalDateTime localDateTime
    ) {
        return Timestamp
            .newBuilder()
            .setSeconds(localDateTime.toEpochSecond(UTC))
            .build();
    }
}
