/*
 * POSEIDON: an agent-based model of fisheries
 * Copyright (c) 2025, University of Oxford.
 *
 * University of Oxford means the Chancellor, Masters and Scholars of the
 * University of Oxford, having an administrative office at Wellington
 * Square, Oxford OX1 2JD, UK.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.project.surimi.poseidon.server;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import com.beust.jcommander.ParameterException;
import io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder;
import io.grpc.protobuf.services.ProtoReflectionServiceV1;
import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.instrumentation.grpc.v1_6.GrpcTelemetry;
import uk.ac.ox.poseidon.core.utils.CustomPathConverter;
import uk.ac.ox.poseidon.io.ScenarioLoader;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.file.Path;
import java.util.Arrays;

import static java.lang.System.Logger.Level.INFO;

public class Server {

    private static final System.Logger logger = System.getLogger(Server.class.getName());

    @Parameter(
        names = {"-s", "--scenario"},
        description = "Path to the scenario file in YAML format.",
        converter = CustomPathConverter.class,
        required = true
    )
    private Path scenarioPath;

    @Parameter(
        names = {"-p", "--port"},
        description = "Port to listen on for gRPC requests.",
        required = true
    )
    private int port;

    public static void main(final String[] args) {
        logger.log(INFO, () -> "Received arguments: " + Arrays.toString(args));
        final Server server = new Server();
        final JCommander jCommander = JCommander
            .newBuilder()
            .addObject(server)
            .build();
        try {
            jCommander.parse(args);
            server.startServer();
        } catch (final ParameterException | IOException | InterruptedException e) {
            System.err.println(e.getMessage());
        }
    }

    private void startServer() throws IOException, InterruptedException {
        final OpenTelemetry openTelemetry = OpenTelemetryConfiguration.initOpenTelemetry();
        final SimulationManager simulationManager = new SimulationManager();
        // Bind to 0.0.0.0 so the server listens on all network interfaces
        @SuppressWarnings("deprecation") final io.grpc.Server grpcServer = NettyServerBuilder
            .forAddress(new InetSocketAddress("0.0.0.0", this.port))
            //.addService(ProtoReflectionService.newInstance()) // deprecated, but works with
            // postman
            .addService(ProtoReflectionServiceV1.newInstance())
            .intercept(new ExceptionInterceptor())
            .intercept(GrpcTelemetry.create(openTelemetry).newServerInterceptor())
            .addService(createAgentsService(simulationManager))
            .addService(createWorkflowService(simulationManager))
            .addService(createEcologyService(simulationManager))
            .build();
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            logger.log(INFO, "Shutting down gRPC server...");
            grpcServer.shutdown();
            logger.log(INFO, "Server shut down.");
        }));
        grpcServer.start();
        logger.log(INFO, "Server started, listening on " + port);
        grpcServer.awaitTermination();
    }

    private AgentsService createAgentsService(final SimulationManager simulationManager) {
        return new AgentsService(
            new GetSalesSummaryRequestHandler(simulationManager),
            new GetCatchDispositionSummaryRequestHandler(simulationManager)
        );
    }

    private EcologyService createEcologyService(final SimulationManager simulationManager) {
        return new EcologyService(
            new GetBiomassRequestHandler(simulationManager)
        );
    }

    private WorkflowService createWorkflowService(final SimulationManager simulationManager) {
        return new WorkflowService(
            new InitRequestHandler(
                simulationManager,
                new ScenarioLoader("eu.project.surimi"),
                scenarioPath.toFile()
            ),
            new SimulateStepRequestHandler(simulationManager),
            new UpdatePricesRequestHandler(simulationManager),
            new UpdateBiomassRequestHandler(simulationManager)
        );
    }

}
